name: PTT IVE Alert

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:
  
permissions:
  contents: write

jobs:

  check:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install
        run: |
          pip install -r requirements.txt


      - name: Run
        env:
          DISCORD_WEBHOOK:
            ${{ secrets.DISCORD_WEBHOOK }}

        run: |
          python main.py


      - name: Save seen
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add seen.json

          git commit -m "update seen" || exit 0

          git push
